sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 0

  alioss:
    access-key-id: LTAI5tDNSsRrr22NRC1TwqKz
    access-key-secret: KofT165EOBHKiciPHPUcxR4e3Qrkpn
    bucket-name: firstld
    endpoint: oss-cn-chengdu.aliyuncs.com

  wechat:
    appid: wx6a7c12b3d3c7d717
    secret: 6b3e0ca6dcc3ed540aac237c3dbb449c
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
