sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 0

  alioss:
    access-key-id: LTAI5tDNSsRrr22NRC1TwqKz
    access-key-secret: KofT165EOBHKiciPHPUcxR4e3Qrkpn
    bucket-name: firstld
    endpoint: oss-cn-chengdu.aliyuncs.com

  wechat:
    appid: wx6a7c12b3d3c7d717
    secret: 6b3e0ca6dcc3ed540aac237c3dbb449c
